data_ingestion:
  test_size: 0.20
  
model_building:
  max_features: 10000
  ngram_range: [1, 3]

stacking_classifier:
  n_splits: 5
  n_jobs: 1
  
  base_learners:
    lgbm:
      objective: 'multiclass'
      num_class: 3
      class_weight: 'balanced'
      verbose: -1
    xgb:
      objective: 'multi:softprob'
      num_class: 3
      eval_metric: 'mlogloss'
      use_label_encoder: False # Set to False to avoid a deprecation warning
    svc:
      probability: True
      class_weight: 'balanced'
      
  meta_model:
    knn:
      n_neighbors: 5