name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      DVC_SECRET_ACCESS_KEY: ${{ secrets.DAGSHUB_PAT }}
      DVC_ACCESS_KEY_ID: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PAT }}
      MLFLOW_TRACKING_URI: 'https://dagshub.com/satyajeetrai007/Youtube-Comment-Sentiment-Analysis.mlflow'
      DVC_REMOTE_URL: 'https://dagshub.com/satyajeetrai007/Youtube-Comment-Sentiment-Analysis.dvc'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements.txt

      - name: Run Pipeline
        run: dvc repro

      - name: Push DVC-tracked data to remote
        run: dvc push

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes to Git
        run: git add .

      - name: Commit changes
        if: github.actor != 'github-actions[bot]'
        continue-on-error: true
        run: |
          git commit -m "Automated commit of DVC outputs and updated code" || echo "No changes to commit"

      - name: Push changes
        if: github.actor != 'github-actions[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ github.ref_name }}