name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-versions: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline
        env:
          MLFLOW_TRACKING_PASSWORD: ${ {secrets.MLFLOW_TRACKING_PASSWORD }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        run: |
          dvc repro


